### ISSUE TITLE
Request Sample App

### ISSUE THREAD

**Issue by DionGanteng** [tim06/VPNProtocols#2]
Good job friend, I'm interested in using this library. I'm new to android programming, there's no complete documentation. I'm confused where to start.
how to add ovpn profile? how to limit only certain apps that can use vpn connection?

**Comment by tim06** [comment]
Hello! Thank you for you interest. You can look to app module, here you can find working sample with modern recommendations. Here you can choose two options:
1. Implementation with jetpack compose — _compose_ package
2. Implementation with Android View — _view_ package

Finally you can build and install app to device, then add .ovpn configuration params. 
Note: Currently ca,cert,key,tls-crypt keys implemented with String type and without keystore.

Allowed apps feature is not implemented now.

**Comment by tim06** [comment]
app module renamed to sample
