### ISSUE TITLE
App crashes when trying to use this library

### ISSUE THREAD

**Issue by DionGanteng** [tim06/VPNProtocols#3]
Crash report taken from logcat
java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

**Comment by tim06** [comment]
Hello! Thank you for issue. Could you show which library(openvpn/shadowsocksr) added in build.gradle file in you project?

**Comment by DionGanteng** [comment]
All, shadowsock and ovpn

**Comment by DionGanteng** [comment]
And this is when I want to add config
![ssr](https://user-images.githubusercontent.com/90413637/186093898-44c56c57-a297-4d06-823c-d6b1e530ead0.png)

**Comment by DionGanteng** [comment]
Type checking has run into a recursive problem. Easiest workaround: specify types of your declarations explicitly

**Comment by tim06** [comment]
Are you using this in activity or fragment? Can you provide more information about this class? Now for this delegate require Context scope

**Comment by DionGanteng** [comment]
I use it in activity class

**Comment by tim06** [comment]
<img width="1010" alt="Снимок экрана 2022-08-29 в 10 00 28" src="https://user-images.githubusercontent.com/9661497/187142300-37d1749a-9bac-4db6-b8eb-2f07706d23df.png">
Here I have created an activity and used the library without error. How can I reproduce your issue?

**Comment by tim06** [comment]
Fixed in 1.0.14 versions

**Comment by DionGanteng** [comment]
Thank you for the response and the update
