### ISSUE TITLE
Android keyboard closes immediately after selecting certain text input

### ISSUE THREAD

**Issue by Mathiaszero** [tim06/VPNProtocols#5]
Hello, when running in android studio, the keyboard closes immediately if i select a text input entry below "Ca," when the user is configuring the ovpn settings.  However, any text input entry for "Ca" and above, the keyboard will remain on the screen.  Am not sure how to figure this out.

There was an output that mentioned "enableOnBackInvokedCallback," so I enabled that in the manifest file, but did not resolve the issue.

**Comment by tim06** [comment]
Good day! This functionality was implemented only to demonstrate the integration of the library into the application, you can use any ui implementation when working with the library. At the moment I can suggest using the view implementation in the updated version 1.1.0
