### ISSUE TITLE
thread interrupt, destroy process

### ISSUE THREAD

**Issue by Yudnikov-Leonid** [tim06/VPNProtocols#7]
When I run shadowsocksR.start(), this is in the console
![image](https://github.com/user-attachments/assets/2c3007ff-921d-4d2b-9fc9-f1cfb9224ef1)
The vpn icon appears in the status bar, status is "connection". After sendFd failed the icon disappears and the status is "disconnected"

Manifest:
![image](https://github.com/user-attachments/assets/bcadf395-273c-457c-99cf-419411e12128)
emulator pixel 6 android 12 (api level 31)

What could the problem be?

Maybe I wrote something wrong here
![image](https://github.com/user-attachments/assets/32d1aebd-3557-4aa2-9ea1-5e777d24397b)

**Comment by tim06** [comment]
Good day, please try to run on your device, because currently there are problems with running on emulators, I recommend you to try the new version 1.1.0
